# Generated by Django 3.1.2 on 2020-11-02 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baike', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child_menu',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baike.bk_menu', verbose_name='上级栏目'),
        ),
    ]
