# Generated by Django 3.1.2 on 2020-11-02 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('baike', '0002_child_menu_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='baike.child_menu', verbose_name='上级栏目'),
        ),
    ]
